-- supabase/seed.sql — GENERATED by scripts/build-seed.mjs. Re-runnable.
-- One active subject (Python) with real OPPE-style questions, plus
-- two inactive subjects to demonstrate the is_active release switch.
set client_min_messages to warning;

do $$
declare
  v_subject uuid;
  v_topic uuid;
begin
  insert into subjects(slug,name,short_code,description,is_active,sort_order) values('python','Programming in Python','PY','Core Python for the OPPE: input handling, control flow, strings, collections, and functions. Timed, exam-style problems.',true,1) on conflict(slug) do update set name=excluded.name, short_code=excluded.short_code, description=excluded.description, is_active=excluded.is_active, sort_order=excluded.sort_order returning id into v_subject;
  delete from questions where subject_id = v_subject;
  delete from topics where subject_id = v_subject;

  insert into topics(subject_id,name,week,sort_order) values(v_subject,'Basics & I/O',1,1) returning id into v_topic;
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Rectangle Perimeter and Area','Read the integer length and breadth of a rectangle and print its perimeter and area.

### Input format
Two integers, each on its own line: the length on the first line and the breadth on the second line.

### Output format
Two lines. The first line is the perimeter `2 * (length + breadth)`. The second line is the area `length * breadth`.

### Example
```
5
3
```
```
16
15
```','easy','coding','Read both integers with `int(input())`, then apply the perimeter and area formulas and print each result on its own line.

```python
length = int(input())
breadth = int(input())
print(2 * (length + breadth))
print(length * breadth)
```',array['input','arithmetic','print','integers']::text[],1);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Integer and Float Division of Two Numbers','Read two integers `a` and `b` (with `b` non-zero) and print the results of integer division, the remainder, and true (float) division.

### Input format
Two integers separated by a single space on one line: `a` then `b`.

### Output format
Three lines:
1. `a // b` (floor division, an integer)
2. `a % b` (remainder, an integer)
3. `a / b` (true division) rounded to exactly 2 decimal places

### Example
```
17 5
```
```
3
2
3.40
```

### Example
```
-17 5
```
```
-4
3
-3.40
```','medium','coding','Split the single input line into two integers. Use `//` for floor division and `%` for the remainder (both follow Python''s floor semantics, so negative operands round toward negative infinity). Format the true division with an f-string using `:.2f` to guarantee two decimals.

```python
a, b = map(int, input().split())
print(a // b)
print(a % b)
print(f"{a / b:.2f}")
```',array['division','modulo','f-strings','rounding']::text[],2);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Split a Bill Evenly','A total bill amount and a number of people are given. Compute each person''s share rounded to 2 decimal places, and also report the leftover paise (cents) that cannot be split evenly when working in whole paise.

Treat the bill as a floating-point rupee amount. Convert it to an integer number of paise using `round(total * 100)`. Divide those paise as evenly as possible among the people: each person pays `paise // people` paise, and `paise % people` paise remain unassigned.

### Input format
Two lines:
- Line 1: a floating-point number `total` (the bill in rupees).
- Line 2: an integer `people` (number of people, at least 1).

### Output format
Two lines:
1. Each person''s share in rupees, printed with exactly 2 decimal places (the per-person paise divided by 100).
2. The number of leftover paise that could not be evenly divided.

### Example
```
100.00
3
```
```
33.33
1
```

### Example
```
50.50
2
```
```
25.25
0
```','medium','coding','Read the total as `float` and people as `int`. Convert rupees to integer paise with `round(total * 100)` to avoid binary floating-point drift. Integer-divide by the number of people for the per-person paise and take the modulus for the leftover. Print the per-person share back in rupees with an f-string using `:.2f`.

```python
total = float(input())
people = int(input())
paise = round(total * 100)
share = paise // people
leftover = paise % people
print(f"{share / 100:.2f}")
print(leftover)
```',array['type-conversion','division','rounding','f-strings']::text[],3);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Temperature Conversion Report','Read a temperature in Celsius and produce a formatted conversion report to Fahrenheit and Kelvin.

Use the formulas:
- Fahrenheit: `F = C * 9 / 5 + 32`
- Kelvin: `K = C + 273.15`

### Input format
A single line containing one floating-point number `C`, the temperature in Celsius.

### Output format
Three lines, each in the exact form `LABEL: VALUE UNIT`:
1. `Celsius: <C> C`
2. `Fahrenheit: <F> F`
3. `Kelvin: <K> K`

Every numeric value must be printed with exactly one digit after the decimal point. The label, colon, single space, value, single space, and unit letter must appear exactly as shown.

### Example
```
37
```
```
Celsius: 37.0 C
Fahrenheit: 98.6 F
Kelvin: 310.2 K
```

### Example
```
-40
```
```
Celsius: -40.0 C
Fahrenheit: -40.0 F
Kelvin: 233.2 K
```','hard','coding','Read `C` as a float, apply both conversion formulas, and print three lines using f-strings with `:.1f` so each value shows exactly one decimal place. The `.1f` format also rounds correctly (e.g. 273.15 becomes 233.2 after adding -40).

```python
c = float(input())
f = c * 9 / 5 + 32
k = c + 273.15
print(f"Celsius: {c:.1f} C")
print(f"Fahrenheit: {f:.1f} F")
print(f"Kelvin: {k:.1f} K")
```',array['type-conversion','f-strings','rounding','arithmetic']::text[],4);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Result Type of a Division Expression','In Python 3, consider the following statements executed one after another:

```python
a = 10
b = 4
x = a / b
y = a // b
z = a % b
```

What are the types of `x`, `y`, and `z` respectively?

- A. `int`, `int`, `int`
- B. `float`, `int`, `int`
- C. `float`, `float`, `float`
- D. `float`, `int`, `float`','medium','mcq','Correct answer: **B**. In Python 3 true division `/` always produces a `float` (so `x` is `float`, value `2.5`), while floor division `//` and modulo `%` on two `int` operands both return `int` (`y` is `2`, `z` is `2`).',array['division','numeric-types','type-conversion']::text[],5);

  insert into topics(subject_id,name,week,sort_order) values(v_subject,'Conditionals & Loops',2,2) returning id into v_topic;
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Count Digits Divisible by Three','You are given a single non-negative integer `N`. Count how many of its decimal digits are divisible by 3. Treat the digit `0` as divisible by 3.

## Input format
A single line containing a non-negative integer `N`.

## Output format
A single line: the count of digits of `N` that are divisible by 3.

## Example
```
360925
```
```
3
```
The digits are 3, 6, 0, 9, 2, 5. Of these, 3, 6, 0 and 9 are divisible by 3, giving a count of 4.

## Example
```
147
```
```
1
```
Only the digit 3 is divisible by 3.','easy','coding','Iterate over the characters of the input string, convert each to an integer, and increment a counter when the digit modulo 3 is 0. Reading `N` as a string avoids any arithmetic on the number itself.

```python
n = input().strip()
count = 0
for ch in n:
    if int(ch) % 3 == 0:
        count += 1
print(count)
```',array['loops','accumulation','digits','modulo']::text[],1);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'First Index Where Running Sum Exceeds Threshold','You are given an integer `T` (a threshold) and a list of `N` integers. Read the integers one at a time and maintain a running sum. Print the 1-based index of the first element after which the running sum becomes strictly greater than `T`. If the running sum never exceeds `T`, print `-1`.

## Input format
- Line 1: two integers `N` and `T` separated by a space.
- Line 2: `N` space-separated integers.

## Output format
A single line: the 1-based index of the first element at which the cumulative sum exceeds `T`, or `-1` if no such index exists.

## Example
```
5 10
2 3 4 5 6
```
```
4
```
Running sums are 2, 5, 9, 14, 20. The first that exceeds 10 is 14, at index 4.

## Example
```
3 100
10 20 30
```
```
-1
```
The total is 60, which never exceeds 100.','medium','coding','Accumulate the sum while looping with an index counter. Break out of the loop and print the index as soon as the running sum exceeds `T`; if the loop finishes without breaking, print `-1`. Using a `for/else` block handles the not-found case cleanly.

```python
n, t = map(int, input().split())
values = list(map(int, input().split()))
total = 0
for i in range(n):
    total += values[i]
    if total > t:
        print(i + 1)
        break
else:
    print(-1)
```',array['loops','accumulation','break','for-else']::text[],2);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Collatz Step Count','Given a positive integer `N`, repeatedly apply the Collatz rule until the value reaches 1:

- If the current value is even, divide it by 2.
- If the current value is odd, replace it with 3 times the value plus 1.

Print the number of steps required to reach 1. If `N` is already 1, the answer is 0.

## Input format
A single line containing a positive integer `N`.

## Output format
A single line: the number of steps needed to reduce `N` to 1.

## Example
```
6
```
```
8
```
The sequence is 6, 3, 10, 5, 16, 8, 4, 2, 1, which is 8 steps.

## Example
```
1
```
```
0
```','medium','coding','Use a `while` loop that continues as long as the value is greater than 1, applying the even/odd rule each iteration and counting steps. Integer division `//` keeps the value an integer.

```python
n = int(input())
steps = 0
while n > 1:
    if n % 2 == 0:
        n = n // 2
    else:
        n = 3 * n + 1
    steps += 1
print(steps)
```',array['while-loop','conditionals','simulation']::text[],3);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Loop Control Trace Output','Consider the following program:

```python
total = 0
for i in range(1, 8):
    if i % 4 == 0:
        break
    if i % 2 == 0:
        continue
    total += i
print(total)
```

What does this program print?

- A. 9
- B. 4
- C. 16
- D. 1','medium','mcq','The correct answer is **B. 4**. `i` takes 1 (odd, add -> total 1), 2 (even, `continue`), 3 (odd, add -> total 4), then 4 triggers `break` before any addition, so the loop stops and 4 is printed.',array['control-flow','break','continue','tracing']::text[],4);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Count Strictly Increasing Diagonal Neighbours in a Grid','You are given a grid of `R` rows and `C` columns of integers. Count the number of cells `(i, j)` for which a lower-right diagonal neighbour `(i+1, j+1)` exists and the value at `(i+1, j+1)` is strictly greater than the value at `(i, j)`.

## Input format
- Line 1: two integers `R` and `C` separated by a space.
- Next `R` lines: each contains `C` space-separated integers.

## Output format
A single line: the number of cells whose lower-right diagonal neighbour holds a strictly larger value.

## Example
```
3 3
1 2 3
2 9 4
3 4 9
```
```
2
```
Cell (0,0)=1 has diagonal (1,1)=9 which is larger. Cell (1,1)=9 has diagonal (2,2)=9 which is not strictly larger. Cell (0,1)=2 has diagonal (1,2)=4 which is larger. Other cells with valid diagonals do not qualify, giving a total of 2.

## Example
```
2 2
5 5
5 5
```
```
0
```
The only cell with a diagonal neighbour is (0,0)=5, whose diagonal (1,1)=5 is equal, not larger.','hard','coding','Read the grid into a list of lists. Use a nested loop over rows `0..R-2` and columns `0..C-2` so that the diagonal neighbour `(i+1, j+1)` is always in bounds, and increment a counter when the neighbour is strictly larger.

```python
r, c = map(int, input().split())
grid = [list(map(int, input().split())) for _ in range(r)]
count = 0
for i in range(r - 1):
    for j in range(c - 1):
        if grid[i + 1][j + 1] > grid[i][j]:
            count += 1
print(count)
```',array['nested-loops','grid','counting','conditionals']::text[],5);

  insert into topics(subject_id,name,week,sort_order) values(v_subject,'Strings',3,3) returning id into v_topic;
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Middle Three Characters','You are given a single string `s` whose length is odd and at least 3. Print the three characters located at the exact middle of the string.

The middle three characters are the character at the center index together with its immediate left and right neighbours.

### Input format
A single line containing the string `s`. It contains no leading or trailing spaces and its length is odd (length >= 3).

### Output format
A single line containing exactly the three middle characters.

### Example 1
```
abcde
```
```
bcd
```

### Example 2
```
python
nope
```

Note: the second example is not applicable here; use only odd-length inputs.

### Example 3
```
X
```
For input of length 1 the rules guarantee this will not occur, so you need not handle it.','easy','coding','The center index of an odd-length string is `len(s) // 2`. Slice from one position left of center up to one position right of center (inclusive), i.e. `s[c-1:c+2]`.

```python
s = input()
c = len(s) // 2
print(s[c - 1:c + 2])
```',array['strings','slicing','indexing']::text[],1);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Vowel and Consonant Count','Given a line of text, count how many alphabetic characters are vowels and how many are consonants. Vowels are `a e i o u` (case-insensitive). Non-alphabetic characters (digits, spaces, punctuation) are ignored.

### Input format
A single line of text that may contain letters, digits, spaces and punctuation.

### Output format
Two lines:
- First line: `Vowels: <n>`
- Second line: `Consonants: <m>`

### Example 1
```
Hello, World! 123
```
```
Vowels: 3
Consonants: 7
```

### Example 2
```
AEIOU xyz
```
```
Vowels: 5
Consonants: 3
```','medium','coding','Iterate over each character. Use `.isalpha()` to keep only letters, then test membership of the lowercased character in the vowel set to classify it.

```python
s = input()
vowels = 0
consonants = 0
for ch in s:
    if ch.isalpha():
        if ch.lower() in "aeiou":
            vowels += 1
        else:
            consonants += 1
print(f"Vowels: {vowels}")
print(f"Consonants: {consonants}")
```',array['strings','iteration','case-handling']::text[],2);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Alternating Case Transform','Transform a string so that its letters alternate case: the first letter becomes uppercase, the second lowercase, the third uppercase, and so on. The alternation counts only alphabetic characters; non-alphabetic characters are printed unchanged and do not advance the alternation counter.

### Input format
A single line containing the string `s`.

### Output format
A single line containing the transformed string.

### Example 1
```
hello world
```
```
HeLlO wOrLd
```

Explanation: the letters in order are h,e,l,l,o,w,o,r,l,d and receive cases Upper,lower,Upper,lower,... The space is copied unchanged and does not affect the counter, so `w` (the 6th letter, index 5) is lowercase.

### Example 2
```
ab3cd
```
```
Ab3Cd
```','medium','coding','Keep a counter of letters seen. For each character, if it is alphabetic, upper-case it when the counter is even and lower-case it when odd, then increment the counter; otherwise emit the character unchanged.

```python
s = input()
result = []
i = 0
for ch in s:
    if ch.isalpha():
        result.append(ch.upper() if i % 2 == 0 else ch.lower())
        i += 1
    else:
        result.append(ch)
print("".join(result))
```',array['strings','case-handling','iteration']::text[],3);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Parse and Sum key=value Pairs','You are given a single line containing zero or more `key=value` pairs separated by semicolons. Each key is a lowercase word and each value is a non-negative integer. Keys may repeat. Compute the total sum of values for each distinct key, then print each key with its total sorted alphabetically by key.

There may be surrounding spaces around keys, values, or the whole pairs; trim them. The input line is never empty but may contain a single pair.

### Input format
A single line such as `a=3; b=10 ; a=7`.

### Output format
One line per distinct key, sorted alphabetically, formatted as `<key>=<total>`.

### Example 1
```
a=3; b=10 ; a=7
```
```
a=10
b=10
```

### Example 2
```
x=5
```
```
x=5
```','hard','coding','Split the line on `;` to get pairs, then split each pair on `=` into key and value. Strip whitespace from both parts, accumulate integer values into a dictionary keyed by name, then print keys in sorted order.

```python
line = input()
totals = {}
for pair in line.split(";"):
    pair = pair.strip()
    if not pair:
        continue
    key, value = pair.split("=")
    key = key.strip()
    totals[key] = totals.get(key, 0) + int(value.strip())
for key in sorted(totals):
    print(f"{key}={totals[key]}")
```',array['strings','parsing','dictionary']::text[],4);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Result of Slicing with a Step','Consider the following Python code:

```python
s = "abcdefgh"
print(s[1:7:2])
```

What does this program print?

- A. `bdf`
- B. `bdf`
- C. `aceg`
- D. `bcdefg`','medium','mcq','The correct answer is B.

The slice `s[1:7:2]` starts at index 1 (`b`), stops before index 7, and steps by 2, selecting indices 1, 3, 5 which are `b`, `d`, `f`, giving `bdf`.',array['strings','slicing','mcq']::text[],5);

  insert into topics(subject_id,name,week,sort_order) values(v_subject,'Lists & Dictionaries',4,4) returning id into v_topic;
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Second-Largest Distinct Value','You are given a list of integers. Print the second-largest **distinct** value in the list.

If the list has fewer than two distinct values, print `None`.

## Input format

A single line containing space-separated integers.

## Output format

A single integer: the second-largest distinct value, or `None` if it does not exist.

## Example

```
4 1 4 9 9 2
```

```
4
```

The distinct values sorted descending are `9, 4, 2, 1`; the second-largest is `4`.

```
7 7 7
```

```
None
```','easy','coding','Build a set to drop duplicates, sort the distinct values in descending order, and index the second element. Guard for the case of fewer than two distinct values.

```python
nums = list(map(int, input().split()))
distinct = sorted(set(nums), reverse=True)
if len(distinct) < 2:
    print(None)
else:
    print(distinct[1])
```',array['lists','sets','sorting','aggregation']::text[],1);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Word Frequency Ranking','Read a line of lowercase words separated by spaces. Build a frequency map and print each distinct word with its count.

Output words ordered by **descending count**. Words with the same count are ordered **alphabetically ascending**.

## Input format

A single line of space-separated lowercase words.

## Output format

One line per distinct word in the format `word count`, following the ordering rule above.

## Example

```
apple banana apple cherry banana apple
```

```
apple 3
banana 2
cherry 1
```

```
fig date fig date apple
```

```
date 2
fig 2
apple 1
```','medium','coding','Count occurrences with a dictionary (or `collections.Counter`), then sort the items by a compound key: negative count for descending count, then the word itself for ascending alphabetical order.

```python
from collections import Counter

words = input().split()
counts = Counter(words)
for word, c in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
    print(word, c)
```',array['dictionaries','frequency-map','sorting','comprehensions']::text[],2);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Sort Records by Score then Name','You are given `n` student records. Each record has a name and an integer score. Sort the records by **descending score**; ties are broken by **ascending name**. Print the sorted names, one per line.

## Input format

The first line contains an integer `n`.
Each of the next `n` lines contains a name and a score separated by a space.

## Output format

The `n` names in sorted order, one per line.

## Example

```
4
alice 80
bob 90
carol 80
dan 90
```

```
bob
dan
alice
carol
```

Scores 90 come first (bob, dan by name), then scores 80 (alice, carol by name).','medium','coding','Read each record into a list of `(name, score)` tuples, then sort with a key of `(-score, name)` so score descends while name breaks ties ascending.

```python
n = int(input())
records = []
for _ in range(n):
    parts = input().split()
    name = parts[0]
    score = int(parts[1])
    records.append((name, score))
for name, score in sorted(records, key=lambda r: (-r[1], r[0])):
    print(name)
```',array['lists','tuples','sorting','keys']::text[],3);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Group Sums by Category','You are given `n` transactions. Each transaction has a category and an integer amount. Some amounts may be negative.

Compute the total amount per category. Then print only the categories whose total is **strictly positive**, ordered by **descending total**; ties are broken by **ascending category name**.

## Input format

The first line contains an integer `n`.
Each of the next `n` lines contains a category and an integer amount separated by a space.

## Output format

One line per qualifying category in the format `category total`. If no category has a strictly positive total, print nothing.

## Example

```
5
food 100
travel 50
food -30
travel -80
books 20
```

```
food 70
books 20
```

food totals 70, travel totals -30 (excluded), books totals 20. Sorted by descending total: food (70), books (20).','hard','coding','Accumulate amounts into a dictionary keyed by category. Filter to keys with a strictly positive total, then sort by `(-total, category)` and print.

```python
n = int(input())
totals = {}
for _ in range(n):
    parts = input().split()
    cat = parts[0]
    amt = int(parts[1])
    totals[cat] = totals.get(cat, 0) + amt
positive = [(cat, t) for cat, t in totals.items() if t > 0]
for cat, t in sorted(positive, key=lambda kv: (-kv[1], kv[0])):
    print(cat, t)
```',array['dictionaries','aggregation','filtering','sorting']::text[],4);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Dictionary Method Return Values','Given the following code:

```python
d = {''a'': 1, ''b'': 2}
x = d.get(''c'', 0)
y = d.setdefault(''c'', 9)
z = d.pop(''a'')
print(x, y, z, len(d))
```

What does this program print?

- A. `0 9 1 2`
- B. `0 0 1 2`
- C. `None 9 1 1`
- D. `0 9 1 3`','easy','mcq','The correct answer is **A**.

`d.get(''c'', 0)` returns `0` without modifying `d` (key absent). `d.setdefault(''c'', 9)` inserts `''c'': 9` and returns `9`. `d.pop(''a'')` removes and returns `1`. After inserting `''c''` and removing `''a''`, `d` is `{''b'': 2, ''c'': 9}`, so `len(d)` is `2`. Output: `0 9 1 2`.',array['dictionaries','methods','get','setdefault']::text[],5);

  insert into topics(subject_id,name,week,sort_order) values(v_subject,'Functions',5,5) returning id into v_topic;
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Rectangle area with a default unit price','Write a function `total_cost(length, width, rate=50)` that returns the area of a rectangle multiplied by a per-unit `rate`. The `rate` parameter must default to `50`.

Read `length` and `width` from standard input. If a third value is present on the input, use it as `rate`; otherwise the default applies. Print the value returned by the function.

## Input format

A single line containing two or three integers separated by spaces: `length width` or `length width rate`.

## Output format

A single integer: the total cost.

## Example

```
4 3
```

```
600
```

```
4 3 10
```

```
120
```','easy','coding','Split the input line. When only two values are given, call the function so the default `rate=50` is used; when three are given, pass the third as `rate`. The area is `length * width`.

```python
def total_cost(length, width, rate=50):
    return length * width * rate

values = list(map(int, input().split()))
if len(values) == 2:
    print(total_cost(values[0], values[1]))
else:
    print(total_cost(values[0], values[1], values[2]))
```',array['functions','default-arguments','return-values']::text[],1);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Recursive digit sum until a single digit','Write a recursive function `digit_root(n)` that repeatedly sums the decimal digits of a non-negative integer `n` until a single digit remains, and returns that digit. You must not use any loop; the repetition must come from recursion.

## Input format

A single line containing one non-negative integer `n`.

## Output format

A single integer between 0 and 9: the digital root of `n`.

## Example

```
9875
```

```
2
```

```
0
```

```
0
```','medium','coding','Base case: if `n` is a single digit (`n < 10`), return `n`. Otherwise sum the digits and recurse on that smaller sum. Summing the digits can itself be written recursively, but computing the digit sum with `sum(int(d) for d in str(n))` inside a recursive outer call keeps the required repetition recursive.

```python
def digit_root(n):
    if n < 10:
        return n
    s = sum(int(d) for d in str(n))
    return digit_root(s)

n = int(input())
print(digit_root(n))
```',array['functions','recursion','digits']::text[],2);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Scope of a name reassigned inside a function','Consider the following program:

```python
x = 5

def f():
    x = x + 1
    return x

print(f())
```

What happens when this program runs?

- A. It prints `6`.
- B. It prints `5`.
- C. It raises `UnboundLocalError`.
- D. It raises `NameError` for `f`.','medium','mcq','Correct answer: C. Because `x` is assigned inside `f`, Python treats `x` as a local variable throughout `f`; the right-hand side `x + 1` then reads a local `x` that has not yet been assigned, raising `UnboundLocalError`.',array['functions','scope','local-variables']::text[],3);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Compose helper functions to validate an ISBN-style checksum','Build the solution from small helpers. Write `weighted_sum(digits)` that returns the sum of each digit multiplied by its 1-based position (first digit times 1, second times 2, and so on), and `is_valid(digits)` that returns `True` when `weighted_sum(digits)` is divisible by 11. The main program reads the digits and prints the result of `is_valid`.

## Input format

A single line containing a string of decimal digits (no spaces).

## Output format

Print `Valid` if the weighted sum is divisible by 11, otherwise print `Invalid`.

## Example

```
132
```

```
Valid
```

```
123
```

```
Invalid
```','medium','coding','`weighted_sum` enumerates the digits with 1-based positions and accumulates `position * digit`. `is_valid` composes it with a divisibility test. The main block converts the input string into a list of integer digits and reports the outcome.

```python
def weighted_sum(digits):
    return sum((i + 1) * d for i, d in enumerate(digits))

def is_valid(digits):
    return weighted_sum(digits) % 11 == 0

s = input().strip()
digits = [int(c) for c in s]
print("Valid" if is_valid(digits) else "Invalid")
```',array['functions','helper-functions','composition']::text[],4);
  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order) values(v_subject,v_topic,'Count paths in a grid using recursion with memoization','A robot starts at the top-left cell `(0, 0)` of an `m` by `n` grid and may move only right or down one cell at a time. Some cells are blocked and cannot be entered. Write a recursive function `count_paths(r, c)` that returns the number of distinct paths from `(r, c)` to the bottom-right cell `(m-1, n-1)`. Use recursion, and avoid recomputation by caching results (for example with a dictionary or `functools.lru_cache`).

## Input format

The first line contains two integers `m` and `n`. Each of the next `m` lines contains `n` integers separated by spaces: `0` for an open cell and `1` for a blocked cell.

It is guaranteed that the start and end cells are open unless stated otherwise; if either is blocked the answer is `0`.

## Output format

A single integer: the number of distinct paths from the top-left to the bottom-right cell.

## Example

```
3 3
0 0 0
0 1 0
0 0 0
```

```
2
```

```
2 2
0 1
1 0
```

```
0
```','hard','coding','Define `count_paths(r, c)` recursively: return `0` if the cell is out of bounds or blocked, return `1` at the destination, otherwise return the sum of moving down and moving right. Memoize on `(r, c)` so each cell is solved once, giving `O(m*n)` work.

```python
import sys
from functools import lru_cache

def main():
    data = sys.stdin.read().split()
    idx = 0
    m = int(data[idx]); idx += 1
    n = int(data[idx]); idx += 1
    grid = []
    for _ in range(m):
        row = [int(data[idx + j]) for j in range(n)]
        idx += n
        grid.append(row)

    @lru_cache(maxsize=None)
    def count_paths(r, c):
        if r >= m or c >= n or grid[r][c] == 1:
            return 0
        if r == m - 1 and c == n - 1:
            return 1
        return count_paths(r + 1, c) + count_paths(r, c + 1)

    print(count_paths(0, 0))

main()
```',array['functions','recursion','memoization','grid']::text[],5);

  insert into subjects(slug,name,short_code,description,is_active,sort_order) values('pdsa','Data Structures & Algorithms with Python','PDSA','Algorithmic problem solving and data structures in Python. Releasing soon.',false,2) on conflict(slug) do update set name=excluded.name, short_code=excluded.short_code, description=excluded.description, is_active=excluded.is_active, sort_order=excluded.sort_order;
  insert into subjects(slug,name,short_code,description,is_active,sort_order) values('dbms','Database Management Systems','DBMS','SQL and relational modelling for the DBMS OPPE. Releasing soon.',false,3) on conflict(slug) do update set name=excluded.name, short_code=excluded.short_code, description=excluded.description, is_active=excluded.is_active, sort_order=excluded.sort_order;
end $$;
