// GENERATED by scripts/gen-databases.mjs from scripts/dbms-databases.json.
// Do not edit by hand — edit the JSON and re-run the generator.
//
// Table metadata only. The DDL and seed data that create these databases live
// in the JSON and are baked into each question's setup_sql at import time.

import type { SchemaTable } from "@/lib/databases";

export interface SchemaDatabase {
  key: string;
  label: string;
  blurb: string;
  tables: SchemaTable[];
}

export const flis: SchemaDatabase = {
  key: "flis",
  label: "FLIS",
  blurb: "Football League Information System — teams and their managers, the players on them, the matches they play, and the referees who officiate.",
  tables: [
  {
    name: "teams",
    columns: [
      { name: "team_id", type: "varchar(10)", pk: true, fk: null },
      { name: "name", type: "varchar(80)", pk: false, fk: null },
      { name: "city", type: "varchar(80)", pk: false, fk: null },
      { name: "playground", type: "varchar(80)", pk: false, fk: null },
      { name: "jersey_home_color", type: "varchar(80)", pk: false, fk: null },
      { name: "jersey_away_color", type: "varchar(80)", pk: false, fk: null },
    ],
  },
  {
    name: "players",
    columns: [
      { name: "player_id", type: "varchar(10)", pk: true, fk: null },
      { name: "name", type: "varchar(80)", pk: false, fk: null },
      { name: "dob", type: "date", pk: false, fk: null },
      { name: "jersey_no", type: "integer", pk: false, fk: null },
      { name: "team_id", type: "varchar(10)", pk: false, fk: "teams.team_id" },
    ],
  },
  {
    name: "managers",
    columns: [
      { name: "mgr_id", type: "varchar(10)", pk: true, fk: null },
      { name: "name", type: "varchar(80)", pk: false, fk: null },
      { name: "dob", type: "date", pk: false, fk: null },
      { name: "team_id", type: "varchar(10)", pk: false, fk: "teams.team_id" },
      { name: "since", type: "date", pk: false, fk: null },
    ],
  },
  {
    name: "matches",
    columns: [
      { name: "match_num", type: "varchar(10)", pk: true, fk: null },
      { name: "match_date", type: "date", pk: false, fk: null },
      { name: "host_team_id", type: "varchar(10)", pk: false, fk: "teams.team_id" },
      { name: "guest_team_id", type: "varchar(10)", pk: false, fk: "teams.team_id" },
      { name: "host_team_score", type: "integer", pk: false, fk: null },
      { name: "guest_team_score", type: "integer", pk: false, fk: null },
    ],
  },
  {
    name: "referees",
    columns: [
      { name: "referee_id", type: "varchar(10)", pk: true, fk: null },
      { name: "name", type: "varchar(80)", pk: false, fk: null },
      { name: "dob", type: "date", pk: false, fk: null },
    ],
  },
  {
    name: "match_referees",
    columns: [
      { name: "match_num", type: "varchar(10)", pk: true, fk: "matches.match_num" },
      { name: "referee", type: "varchar(10)", pk: false, fk: "referees.referee_id" },
      { name: "assistant_referee_1", type: "varchar(10)", pk: false, fk: "referees.referee_id" },
      { name: "assistant_referee_2", type: "varchar(10)", pk: false, fk: "referees.referee_id" },
      { name: "fourth_referee", type: "varchar(10)", pk: false, fk: "referees.referee_id" },
    ],
  },
  ],
};

export const lis: SchemaDatabase = {
  key: "lis",
  label: "LIS",
  blurb: "Library Information System — the book catalogue and its physical copies, the members who borrow them, and the quota each member type gets.",
  tables: [
  {
    name: "departments",
    columns: [
      { name: "department_code", type: "varchar(4)", pk: true, fk: null },
      { name: "department_name", type: "varchar(80)", pk: false, fk: null },
      { name: "department_building", type: "varchar(80)", pk: false, fk: null },
    ],
  },
  {
    name: "staff",
    columns: [
      { name: "staff_fname", type: "varchar(80)", pk: false, fk: null },
      { name: "staff_lname", type: "varchar(80)", pk: false, fk: null },
      { name: "id", type: "varchar(20)", pk: true, fk: null },
      { name: "gender", type: "varchar(1)", pk: false, fk: null },
      { name: "doj", type: "date", pk: false, fk: null },
      { name: "mobile_no", type: "numeric(10)", pk: false, fk: null },
    ],
  },
  {
    name: "quota",
    columns: [
      { name: "member_type", type: "varchar(2)", pk: true, fk: null },
      { name: "max_books", type: "int", pk: false, fk: null },
      { name: "max_duration", type: "int", pk: false, fk: null },
    ],
  },
  {
    name: "members",
    columns: [
      { name: "member_no", type: "varchar(20)", pk: true, fk: null },
      { name: "member_class", type: "varchar(20)", pk: false, fk: null },
      { name: "member_type", type: "varchar(2)", pk: false, fk: "quota.member_type" },
      { name: "roll_no", type: "varchar(20)", pk: false, fk: null },
      { name: "id", type: "varchar(20)", pk: false, fk: null },
    ],
  },
  {
    name: "students",
    columns: [
      { name: "student_fname", type: "varchar(80)", pk: false, fk: null },
      { name: "student_lname", type: "varchar(80)", pk: false, fk: null },
      { name: "roll_no", type: "varchar(20)", pk: true, fk: null },
      { name: "department_code", type: "varchar(4)", pk: false, fk: "departments.department_code" },
      { name: "gender", type: "varchar(1)", pk: false, fk: null },
      { name: "dob", type: "date", pk: false, fk: null },
      { name: "degree", type: "varchar(80)", pk: false, fk: null },
      { name: "mobile_no", type: "numeric(10)", pk: false, fk: null },
    ],
  },
  {
    name: "faculty",
    columns: [
      { name: "faculty_fname", type: "varchar(80)", pk: false, fk: null },
      { name: "faculty_lname", type: "varchar(80)", pk: false, fk: null },
      { name: "id", type: "varchar(20)", pk: true, fk: null },
      { name: "department_code", type: "varchar(4)", pk: false, fk: "departments.department_code" },
      { name: "gender", type: "varchar(1)", pk: false, fk: null },
      { name: "doj", type: "date", pk: false, fk: null },
      { name: "mobile_no", type: "numeric(10)", pk: false, fk: null },
    ],
  },
  {
    name: "book_catalogue",
    columns: [
      { name: "isbn_no", type: "varchar(13)", pk: true, fk: null },
      { name: "title", type: "varchar(256)", pk: false, fk: null },
      { name: "publisher", type: "varchar(80)", pk: false, fk: null },
      { name: "year", type: "int", pk: false, fk: null },
    ],
  },
  {
    name: "book_copies",
    columns: [
      { name: "isbn_no", type: "varchar(13)", pk: false, fk: "book_catalogue.isbn_no" },
      { name: "accession_no", type: "varchar(20)", pk: true, fk: null },
    ],
  },
  {
    name: "book_issue",
    columns: [
      { name: "member_no", type: "varchar(20)", pk: true, fk: "members.member_no" },
      { name: "accession_no", type: "varchar(20)", pk: true, fk: "book_copies.accession_no" },
      { name: "doi", type: "date", pk: false, fk: null },
    ],
  },
  {
    name: "book_authors",
    columns: [
      { name: "isbn_no", type: "varchar(13)", pk: true, fk: "book_catalogue.isbn_no" },
      { name: "author_fname", type: "varchar(80)", pk: true, fk: null },
      { name: "author_lname", type: "varchar(80)", pk: true, fk: null },
    ],
  },
  ],
};

export const university: SchemaDatabase = {
  key: "university",
  label: "University",
  blurb: "The university schema from Silberschatz: departments run courses, courses have sections timetabled into classrooms, and students take what instructors teach.",
  tables: [
  {
    name: "classroom",
    columns: [
      { name: "building", type: "varchar(15)", pk: true, fk: null },
      { name: "room_number", type: "varchar(7)", pk: true, fk: null },
      { name: "capacity", type: "numeric(4,0)", pk: false, fk: null },
    ],
  },
  {
    name: "department",
    columns: [
      { name: "dept_name", type: "varchar(20)", pk: true, fk: null },
      { name: "building", type: "varchar(15)", pk: false, fk: null },
      { name: "budget", type: "numeric(12,2)", pk: false, fk: null },
    ],
  },
  {
    name: "course",
    columns: [
      { name: "course_id", type: "varchar(8)", pk: true, fk: null },
      { name: "title", type: "varchar(50)", pk: false, fk: null },
      { name: "dept_name", type: "varchar(20)", pk: false, fk: "department.dept_name" },
      { name: "credits", type: "numeric(2,0)", pk: false, fk: null },
    ],
  },
  {
    name: "instructor",
    columns: [
      { name: "ID", type: "varchar(5)", pk: true, fk: null },
      { name: "name", type: "varchar(20)", pk: false, fk: null },
      { name: "dept_name", type: "varchar(20)", pk: false, fk: "department.dept_name" },
      { name: "salary", type: "numeric(8,2)", pk: false, fk: null },
    ],
  },
  {
    name: "section",
    columns: [
      { name: "course_id", type: "varchar(8)", pk: true, fk: "course.course_id" },
      { name: "sec_id", type: "varchar(8)", pk: true, fk: null },
      { name: "semester", type: "varchar(6)", pk: true, fk: null },
      { name: "year", type: "numeric(4,0)", pk: true, fk: null },
      { name: "building", type: "varchar(15)", pk: false, fk: "classroom.building" },
      { name: "room_number", type: "varchar(7)", pk: false, fk: "classroom.room_number" },
      { name: "time_slot_id", type: "varchar(4)", pk: false, fk: null },
    ],
  },
  {
    name: "teaches",
    columns: [
      { name: "ID", type: "varchar(5)", pk: true, fk: "instructor.ID" },
      { name: "course_id", type: "varchar(8)", pk: true, fk: "section.course_id" },
      { name: "sec_id", type: "varchar(8)", pk: true, fk: "section.sec_id" },
      { name: "semester", type: "varchar(6)", pk: true, fk: "section.semester" },
      { name: "year", type: "numeric(4,0)", pk: true, fk: "section.year" },
    ],
  },
  {
    name: "student",
    columns: [
      { name: "ID", type: "varchar(5)", pk: true, fk: null },
      { name: "name", type: "varchar(20)", pk: false, fk: null },
      { name: "dept_name", type: "varchar(20)", pk: false, fk: "department.dept_name" },
      { name: "tot_cred", type: "numeric(3,0)", pk: false, fk: null },
    ],
  },
  {
    name: "takes",
    columns: [
      { name: "ID", type: "varchar(5)", pk: true, fk: "student.ID" },
      { name: "course_id", type: "varchar(8)", pk: true, fk: "section.course_id" },
      { name: "sec_id", type: "varchar(8)", pk: true, fk: "section.sec_id" },
      { name: "semester", type: "varchar(6)", pk: true, fk: "section.semester" },
      { name: "year", type: "numeric(4,0)", pk: true, fk: "section.year" },
      { name: "grade", type: "varchar(2)", pk: false, fk: null },
    ],
  },
  {
    name: "advisor",
    columns: [
      { name: "s_id", type: "varchar(5)", pk: true, fk: "student.ID" },
      { name: "i_id", type: "varchar(5)", pk: false, fk: "instructor.ID" },
    ],
  },
  {
    name: "time_slot",
    columns: [
      { name: "time_slot_id", type: "varchar(4)", pk: true, fk: null },
      { name: "day", type: "varchar(1)", pk: true, fk: null },
      { name: "start_time", type: "time", pk: true, fk: null },
      { name: "end_time", type: "time", pk: false, fk: null },
    ],
  },
  {
    name: "prereq",
    columns: [
      { name: "course_id", type: "varchar(8)", pk: true, fk: "course.course_id" },
      { name: "prereq_id", type: "varchar(8)", pk: true, fk: "course.course_id" },
    ],
  },
  ],
};

export const bookca: SchemaDatabase = {
  key: "bookca",
  label: "Book Catalogue",
  blurb: "A single catalogue of books, each with its ISBN, publisher and year of publication.",
  tables: [
  {
    name: "book_catalogue",
    columns: [
      { name: "ISBN_no", type: "varchar(13)", pk: true, fk: null },
      { name: "title", type: "varchar(256)", pk: false, fk: null },
      { name: "publisher", type: "varchar(80)", pk: false, fk: null },
      { name: "year", type: "int", pk: false, fk: null },
    ],
  },
  ],
};

export const DATABASES: Record<string, SchemaDatabase> = {
  flis,
  lis,
  university,
  bookca,
};

/** Look up a database by the `db:<key>` tag carried on a paper's questions. */
export function schemaFor(key: string | null | undefined): SchemaDatabase | null {
  if (!key) return null;
  return DATABASES[key] ?? null;
}
