// Build supabase/seed.sql from the authored question set (workflow journal).
//   node scripts/build-seed.mjs <journal.jsonl> [out.sql]
import { readFileSync, writeFileSync } from "node:fs";

const journalPath = process.argv[2];
const outPath = process.argv[3] ?? "supabase/seed.sql";
if (!journalPath) {
  console.error("Usage: node scripts/build-seed.mjs <journal.jsonl> [out.sql]");
  process.exit(2);
}

const lines = readFileSync(journalPath, "utf8").split(/\r?\n/).filter(Boolean);
const topics = [];
for (const line of lines) {
  let obj;
  try {
    obj = JSON.parse(line);
  } catch {
    continue;
  }
  if (obj.type === "result" && obj.result && obj.result.topic_name) {
    topics.push(obj.result);
  }
}

if (topics.length === 0) {
  console.error("No topic results found in journal.");
  process.exit(1);
}

topics.sort((a, b) => (a.week ?? 0) - (b.week ?? 0));

const sq = (s) => "'" + String(s ?? "").replace(/'/g, "''") + "'";
const sqArr = (arr) =>
  "array[" + (arr ?? []).map(sq).join(",") + "]::text[]";

const out = [];
out.push("-- supabase/seed.sql — GENERATED by scripts/build-seed.mjs. Re-runnable.");
out.push("-- One active subject (Python) with real OPPE-style questions, plus");
out.push("-- two inactive subjects to demonstrate the is_active release switch.");
out.push("set client_min_messages to warning;");
out.push("");
out.push("do $$");
out.push("declare");
out.push("  v_subject uuid;");
out.push("  v_topic uuid;");
out.push("begin");

const pyDesc =
  "Core Python for the OPPE: input handling, control flow, strings, collections, and functions. Timed, exam-style problems.";
out.push(
  `  insert into subjects(slug,name,short_code,description,is_active,sort_order)` +
    ` values('python','Programming in Python','PY',${sq(pyDesc)},true,1)` +
    ` on conflict(slug) do update set name=excluded.name, short_code=excluded.short_code,` +
    ` description=excluded.description, is_active=excluded.is_active, sort_order=excluded.sort_order` +
    ` returning id into v_subject;`,
);
out.push("  delete from questions where subject_id = v_subject;");
out.push("  delete from topics where subject_id = v_subject;");
out.push("");

let questionCount = 0;
topics.forEach((t, ti) => {
  out.push(
    `  insert into topics(subject_id,name,week,sort_order)` +
      ` values(v_subject,${sq(t.topic_name)},${Number(t.week) || "null"},${ti + 1})` +
      ` returning id into v_topic;`,
  );
  (t.questions ?? []).forEach((q, qi) => {
    questionCount++;
    out.push(
      `  insert into questions(subject_id,topic_id,title,body_md,difficulty,kind,solution_md,tags,sort_order)` +
        ` values(v_subject,v_topic,${sq(q.title)},${sq(q.body_md)},${sq(q.difficulty)},${sq(q.kind)},${sq(q.solution_md)},${sqArr(q.tags)},${qi + 1});`,
    );
  });
  out.push("");
});

const inactive = [
  {
    slug: "pdsa",
    name: "Data Structures & Algorithms with Python",
    code: "PDSA",
    desc: "Algorithmic problem solving and data structures in Python. Releasing soon.",
    order: 2,
  },
  {
    slug: "dbms",
    name: "Database Management Systems",
    code: "DBMS",
    desc: "SQL and relational modelling for the DBMS OPPE. Releasing soon.",
    order: 3,
  },
];
for (const s of inactive) {
  out.push(
    `  insert into subjects(slug,name,short_code,description,is_active,sort_order)` +
      ` values(${sq(s.slug)},${sq(s.name)},${sq(s.code)},${sq(s.desc)},false,${s.order})` +
      ` on conflict(slug) do update set name=excluded.name, short_code=excluded.short_code,` +
      ` description=excluded.description, is_active=excluded.is_active, sort_order=excluded.sort_order;`,
  );
}

out.push("end $$;");
out.push("");

writeFileSync(outPath, out.join("\n"), "utf8");
console.log(
  `Wrote ${outPath}: ${topics.length} topics, ${questionCount} questions, ${inactive.length} inactive subjects.`,
);
