// Build validated coding test cases (correct expected outputs computed by
// actually running each reference solution in Python) + MCQ structure, and
// emit SQL to populate questions.tests / mcq_options / mcq_answer.
//
//   node scripts/build-tests.mjs <journal.jsonl> <_questions.json> <out.sql>
import { readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

const journalPath = process.argv[2];
const questionsPath = process.argv[3];
const outPath = process.argv[4];

// Collect the per-question workflow items from the journal.
const items = new Map();
for (const line of readFileSync(journalPath, "utf8").split(/\r?\n/)) {
  if (!line.trim()) continue;
  let obj;
  try {
    obj = JSON.parse(line);
  } catch {
    continue;
  }
  if (obj.type === "result" && obj.result && obj.result.id) {
    items.set(obj.result.id, obj.result);
  }
}

const questions = JSON.parse(readFileSync(questionsPath, "utf8"));

function extractPython(md) {
  if (!md) return null;
  const m = md.match(/```python\s*\n([\s\S]*?)```/i);
  return m ? m[1].replace(/\s+$/, "") + "\n" : null;
}

function normalize(s) {
  return s
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((l) => l.replace(/[ \t]+$/, ""))
    .join("\n")
    .replace(/\n+$/, "");
}

function runPython(code, stdin) {
  const res = spawnSync("python", ["-I", "-"], {
    input: `${code}\n`,
    // Pass the program on stdin AFTER the code? No — we run code file via -c is awkward for input().
    encoding: "utf8",
    timeout: 5000,
  });
  return res;
}

// We must feed the program via a file and the test input via stdin. spawnSync
// can only pipe one stdin, so write the program to a temp file per question.
import { mkdtempSync, writeFileSync as wf } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const tmp = mkdtempSync(join(tmpdir(), "oppe-tests-"));

function runProgram(progPath, stdin) {
  const res = spawnSync("python", ["-I", progPath], {
    input: stdin,
    encoding: "utf8",
    timeout: 5000,
  });
  return res;
}

const sq = (s) => "'" + String(s ?? "").replace(/'/g, "''") + "'";
const jsonLit = (obj) => sq(JSON.stringify(obj)) + "::jsonb";

const out = [];
out.push("-- GENERATED by scripts/build-tests.mjs — validated tests + MCQ. Re-runnable.");
out.push("set client_min_messages to warning;");

let codingOk = 0;
let totalTests = 0;
let mcqOk = 0;

for (const q of questions) {
  const item = items.get(q.id);
  if (!item) continue;

  if (q.kind === "coding") {
    const code = extractPython(q.solution_md);
    if (!code) {
      console.warn(`No python solution for ${q.title}`);
      continue;
    }
    const progPath = join(tmp, `${q.index}.py`);
    wf(progPath, code, "utf8");

    const tests = [];
    for (const stdin of item.stdins ?? []) {
      const res = runProgram(progPath, stdin);
      if (res.status !== 0 || res.error || (res.stderr && res.stderr.trim())) {
        // solution errored on this input — skip it
        continue;
      }
      const expected = normalize(res.stdout ?? "");
      tests.push({ stdin, expected });
    }
    // Dedupe by stdin, cap at 6, mark first 2 visible.
    const seen = new Set();
    const deduped = [];
    for (const t of tests) {
      if (seen.has(t.stdin)) continue;
      seen.add(t.stdin);
      deduped.push(t);
    }
    const finalTests = deduped.slice(0, 6).map((t, i) => ({
      stdin: t.stdin,
      expected: t.expected,
      hidden: i >= 2,
    }));
    if (finalTests.length === 0) {
      console.warn(`No valid tests for ${q.title}`);
      continue;
    }
    codingOk++;
    totalTests += finalTests.length;
    out.push(
      `update public.questions set tests = ${jsonLit(finalTests)} where id = ${sq(q.id)};`,
    );
  } else if (q.kind === "mcq") {
    if (!item.options || !item.answerKey) continue;
    mcqOk++;
    out.push(
      `update public.questions set mcq_options = ${jsonLit(item.options)}, mcq_answer = ${sq(item.answerKey)} where id = ${sq(q.id)};`,
    );
  }
}

writeFileSync(outPath, out.join("\n") + "\n", "utf8");
console.log(
  `Wrote ${outPath}: ${codingOk} coding questions (${totalTests} tests), ${mcqOk} mcq.`,
);
